

import { Outfit } from "next/font/google";
import "./globals.css";

const OutfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme='white'
      className={`${OutfitFont.className} h-full antialiased`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
